# Use Python for simplicity
FROM python:3.11-slim

# Install PostgreSQL client library
RUN pip install psycopg2-binary

# Copy script
COPY hello.py /hello.py

# Run script
CMD ["python", "/hello.py"]
